// Code generated  DO NOT EDIT.

package colors

// ACHTUNG: Dieses File ist Teil von 'gg/colors' und wird
// automatisch erzeugt. Manuelle Anpassungn an dieser
// Datei werden bei einem erneuten Generieren überschreiben.

// Alle in der SVG 1.1 Spezifikation benannten Farben sind
// in diesem Package als Variablen definiert.
var (
    AliceBlue                = RGBA{R:0xf0, G:0xf8, B:0xff, A:0xff}
    AntiqueWhite             = RGBA{R:0xfa, G:0xeb, B:0xd7, A:0xff}
    Aqua                     = RGBA{R:0x00, G:0xff, B:0xff, A:0xff}
    Aquamarine               = RGBA{R:0x7f, G:0xff, B:0xd4, A:0xff}
    Azure                    = RGBA{R:0xf0, G:0xff, B:0xff, A:0xff}
    Beige                    = RGBA{R:0xf5, G:0xf5, B:0xdc, A:0xff}
    Bisque                   = RGBA{R:0xff, G:0xe4, B:0xc4, A:0xff}
    Black                    = RGBA{R:0x00, G:0x00, B:0x00, A:0xff}
    BlanchedAlmond           = RGBA{R:0xff, G:0xeb, B:0xcd, A:0xff}
    Blue                     = RGBA{R:0x00, G:0x00, B:0xff, A:0xff}
    BlueViolet               = RGBA{R:0x8a, G:0x2b, B:0xe2, A:0xff}
    Brown                    = RGBA{R:0xa5, G:0x2a, B:0x2a, A:0xff}
    BurlyWood                = RGBA{R:0xde, G:0xb8, B:0x87, A:0xff}
    CadetBlue                = RGBA{R:0x5f, G:0x9e, B:0xa0, A:0xff}
    Chartreuse               = RGBA{R:0x7f, G:0xff, B:0x00, A:0xff}
    Chocolate                = RGBA{R:0xd2, G:0x69, B:0x1e, A:0xff}
    Coral                    = RGBA{R:0xff, G:0x7f, B:0x50, A:0xff}
    CornflowerBlue           = RGBA{R:0x64, G:0x95, B:0xed, A:0xff}
    Cornsilk                 = RGBA{R:0xff, G:0xf8, B:0xdc, A:0xff}
    Crimson                  = RGBA{R:0xdc, G:0x14, B:0x3c, A:0xff}
    Cyan                     = RGBA{R:0x00, G:0xff, B:0xff, A:0xff}
    DarkBlue                 = RGBA{R:0x00, G:0x00, B:0x8b, A:0xff}
    DarkCyan                 = RGBA{R:0x00, G:0x8b, B:0x8b, A:0xff}
    DarkGoldenrod            = RGBA{R:0xb8, G:0x86, B:0x0b, A:0xff}
    DarkGray                 = RGBA{R:0xa9, G:0xa9, B:0xa9, A:0xff}
    DarkGreen                = RGBA{R:0x00, G:0x64, B:0x00, A:0xff}
    DarkGrey                 = RGBA{R:0xa9, G:0xa9, B:0xa9, A:0xff}
    DarkKhaki                = RGBA{R:0xbd, G:0xb7, B:0x6b, A:0xff}
    DarkMagenta              = RGBA{R:0x8b, G:0x00, B:0x8b, A:0xff}
    DarkOliveGreen           = RGBA{R:0x55, G:0x6b, B:0x2f, A:0xff}
    DarkOrange               = RGBA{R:0xff, G:0x8c, B:0x00, A:0xff}
    DarkOrchid               = RGBA{R:0x99, G:0x32, B:0xcc, A:0xff}
    DarkRed                  = RGBA{R:0x8b, G:0x00, B:0x00, A:0xff}
    DarkSalmon               = RGBA{R:0xe9, G:0x96, B:0x7a, A:0xff}
    DarkSeaGreen             = RGBA{R:0x8f, G:0xbc, B:0x8f, A:0xff}
    DarkSlateBlue            = RGBA{R:0x48, G:0x3d, B:0x8b, A:0xff}
    DarkSlateGray            = RGBA{R:0x2f, G:0x4f, B:0x4f, A:0xff}
    DarkSlateGrey            = RGBA{R:0x2f, G:0x4f, B:0x4f, A:0xff}
    DarkTurquoise            = RGBA{R:0x00, G:0xce, B:0xd1, A:0xff}
    DarkViolet               = RGBA{R:0x94, G:0x00, B:0xd3, A:0xff}
    DeepPink                 = RGBA{R:0xff, G:0x14, B:0x93, A:0xff}
    DeepSkyBlue              = RGBA{R:0x00, G:0xbf, B:0xff, A:0xff}
    DimGray                  = RGBA{R:0x69, G:0x69, B:0x69, A:0xff}
    DimGrey                  = RGBA{R:0x69, G:0x69, B:0x69, A:0xff}
    DodgerBlue               = RGBA{R:0x1e, G:0x90, B:0xff, A:0xff}
    FireBrick                = RGBA{R:0xb2, G:0x22, B:0x22, A:0xff}
    FloralWhite              = RGBA{R:0xff, G:0xfa, B:0xf0, A:0xff}
    ForestGreen              = RGBA{R:0x22, G:0x8b, B:0x22, A:0xff}
    Fuchsia                  = RGBA{R:0xff, G:0x00, B:0xff, A:0xff}
    Gainsboro                = RGBA{R:0xdc, G:0xdc, B:0xdc, A:0xff}
    GhostWhite               = RGBA{R:0xf8, G:0xf8, B:0xff, A:0xff}
    Gold                     = RGBA{R:0xff, G:0xd7, B:0x00, A:0xff}
    Goldenrod                = RGBA{R:0xda, G:0xa5, B:0x20, A:0xff}
    Gray                     = RGBA{R:0x80, G:0x80, B:0x80, A:0xff}
    Green                    = RGBA{R:0x00, G:0x80, B:0x00, A:0xff}
    GreenYellow              = RGBA{R:0xad, G:0xff, B:0x2f, A:0xff}
    Grey                     = RGBA{R:0x80, G:0x80, B:0x80, A:0xff}
    Honeydew                 = RGBA{R:0xf0, G:0xff, B:0xf0, A:0xff}
    HotPink                  = RGBA{R:0xff, G:0x69, B:0xb4, A:0xff}
    IndianRed                = RGBA{R:0xcd, G:0x5c, B:0x5c, A:0xff}
    Indigo                   = RGBA{R:0x4b, G:0x00, B:0x82, A:0xff}
    Ivory                    = RGBA{R:0xff, G:0xff, B:0xf0, A:0xff}
    Khaki                    = RGBA{R:0xf0, G:0xe6, B:0x8c, A:0xff}
    Lavender                 = RGBA{R:0xe6, G:0xe6, B:0xfa, A:0xff}
    LavenderBlush            = RGBA{R:0xff, G:0xf0, B:0xf5, A:0xff}
    LawnGreen                = RGBA{R:0x7c, G:0xfc, B:0x00, A:0xff}
    LemonChiffon             = RGBA{R:0xff, G:0xfa, B:0xcd, A:0xff}
    LightBlue                = RGBA{R:0xad, G:0xd8, B:0xe6, A:0xff}
    LightCoral               = RGBA{R:0xf0, G:0x80, B:0x80, A:0xff}
    LightCyan                = RGBA{R:0xe0, G:0xff, B:0xff, A:0xff}
    LightGoldenrodYellow     = RGBA{R:0xfa, G:0xfa, B:0xd2, A:0xff}
    LightGray                = RGBA{R:0xd3, G:0xd3, B:0xd3, A:0xff}
    LightGreen               = RGBA{R:0x90, G:0xee, B:0x90, A:0xff}
    LightGrey                = RGBA{R:0xd3, G:0xd3, B:0xd3, A:0xff}
    LightPink                = RGBA{R:0xff, G:0xb6, B:0xc1, A:0xff}
    LightSalmon              = RGBA{R:0xff, G:0xa0, B:0x7a, A:0xff}
    LightSeaGreen            = RGBA{R:0x20, G:0xb2, B:0xaa, A:0xff}
    LightSkyBlue             = RGBA{R:0x87, G:0xce, B:0xfa, A:0xff}
    LightSlateGray           = RGBA{R:0x77, G:0x88, B:0x99, A:0xff}
    LightSlateGrey           = RGBA{R:0x77, G:0x88, B:0x99, A:0xff}
    LightSteelBlue           = RGBA{R:0xb0, G:0xc4, B:0xde, A:0xff}
    LightYellow              = RGBA{R:0xff, G:0xff, B:0xe0, A:0xff}
    Lime                     = RGBA{R:0x00, G:0xff, B:0x00, A:0xff}
    LimeGreen                = RGBA{R:0x32, G:0xcd, B:0x32, A:0xff}
    Linen                    = RGBA{R:0xfa, G:0xf0, B:0xe6, A:0xff}
    Magenta                  = RGBA{R:0xff, G:0x00, B:0xff, A:0xff}
    Maroon                   = RGBA{R:0x80, G:0x00, B:0x00, A:0xff}
    MediumAquamarine         = RGBA{R:0x66, G:0xcd, B:0xaa, A:0xff}
    MediumBlue               = RGBA{R:0x00, G:0x00, B:0xcd, A:0xff}
    MediumOrchid             = RGBA{R:0xba, G:0x55, B:0xd3, A:0xff}
    MediumPurple             = RGBA{R:0x93, G:0x70, B:0xdb, A:0xff}
    MediumSeaGreen           = RGBA{R:0x3c, G:0xb3, B:0x71, A:0xff}
    MediumSlateBlue          = RGBA{R:0x7b, G:0x68, B:0xee, A:0xff}
    MediumSpringGreen        = RGBA{R:0x00, G:0xfa, B:0x9a, A:0xff}
    MediumTurquoise          = RGBA{R:0x48, G:0xd1, B:0xcc, A:0xff}
    MediumVioletRed          = RGBA{R:0xc7, G:0x15, B:0x85, A:0xff}
    MidnightBlue             = RGBA{R:0x19, G:0x19, B:0x70, A:0xff}
    MintCream                = RGBA{R:0xf5, G:0xff, B:0xfa, A:0xff}
    MistyRose                = RGBA{R:0xff, G:0xe4, B:0xe1, A:0xff}
    Moccasin                 = RGBA{R:0xff, G:0xe4, B:0xb5, A:0xff}
    NavajoWhite              = RGBA{R:0xff, G:0xde, B:0xad, A:0xff}
    Navy                     = RGBA{R:0x00, G:0x00, B:0x80, A:0xff}
    OldLace                  = RGBA{R:0xfd, G:0xf5, B:0xe6, A:0xff}
    Olive                    = RGBA{R:0x80, G:0x80, B:0x00, A:0xff}
    OliveDrab                = RGBA{R:0x6b, G:0x8e, B:0x23, A:0xff}
    Orange                   = RGBA{R:0xff, G:0xa5, B:0x00, A:0xff}
    OrangeRed                = RGBA{R:0xff, G:0x45, B:0x00, A:0xff}
    Orchid                   = RGBA{R:0xda, G:0x70, B:0xd6, A:0xff}
    PaleGoldenrod            = RGBA{R:0xee, G:0xe8, B:0xaa, A:0xff}
    PaleGreen                = RGBA{R:0x98, G:0xfb, B:0x98, A:0xff}
    PaleTurquoise            = RGBA{R:0xaf, G:0xee, B:0xee, A:0xff}
    PaleVioletRed            = RGBA{R:0xdb, G:0x70, B:0x93, A:0xff}
    PapayaWhip               = RGBA{R:0xff, G:0xef, B:0xd5, A:0xff}
    PeachPuff                = RGBA{R:0xff, G:0xda, B:0xb9, A:0xff}
    Peru                     = RGBA{R:0xcd, G:0x85, B:0x3f, A:0xff}
    Pink                     = RGBA{R:0xff, G:0xc0, B:0xcb, A:0xff}
    Plum                     = RGBA{R:0xdd, G:0xa0, B:0xdd, A:0xff}
    PowderBlue               = RGBA{R:0xb0, G:0xe0, B:0xe6, A:0xff}
    Purple                   = RGBA{R:0x80, G:0x00, B:0x80, A:0xff}
    Red                      = RGBA{R:0xff, G:0x00, B:0x00, A:0xff}
    RosyBrown                = RGBA{R:0xbc, G:0x8f, B:0x8f, A:0xff}
    RoyalBlue                = RGBA{R:0x41, G:0x69, B:0xe1, A:0xff}
    SaddleBrown              = RGBA{R:0x8b, G:0x45, B:0x13, A:0xff}
    Salmon                   = RGBA{R:0xfa, G:0x80, B:0x72, A:0xff}
    SandyBrown               = RGBA{R:0xf4, G:0xa4, B:0x60, A:0xff}
    SeaGreen                 = RGBA{R:0x2e, G:0x8b, B:0x57, A:0xff}
    Seashell                 = RGBA{R:0xff, G:0xf5, B:0xee, A:0xff}
    Sienna                   = RGBA{R:0xa0, G:0x52, B:0x2d, A:0xff}
    Silver                   = RGBA{R:0xc0, G:0xc0, B:0xc0, A:0xff}
    SkyBlue                  = RGBA{R:0x87, G:0xce, B:0xeb, A:0xff}
    SlateBlue                = RGBA{R:0x6a, G:0x5a, B:0xcd, A:0xff}
    SlateGray                = RGBA{R:0x70, G:0x80, B:0x90, A:0xff}
    SlateGrey                = RGBA{R:0x70, G:0x80, B:0x90, A:0xff}
    Snow                     = RGBA{R:0xff, G:0xfa, B:0xfa, A:0xff}
    SpringGreen              = RGBA{R:0x00, G:0xff, B:0x7f, A:0xff}
    SteelBlue                = RGBA{R:0x46, G:0x82, B:0xb4, A:0xff}
    Tan                      = RGBA{R:0xd2, G:0xb4, B:0x8c, A:0xff}
    Teal                     = RGBA{R:0x00, G:0x80, B:0x80, A:0xff}
    Thistle                  = RGBA{R:0xd8, G:0xbf, B:0xd8, A:0xff}
    Tomato                   = RGBA{R:0xff, G:0x63, B:0x47, A:0xff}
    Turquoise                = RGBA{R:0x40, G:0xe0, B:0xd0, A:0xff}
    Violet                   = RGBA{R:0xee, G:0x82, B:0xee, A:0xff}
    Wheat                    = RGBA{R:0xf5, G:0xde, B:0xb3, A:0xff}
    White                    = RGBA{R:0xff, G:0xff, B:0xff, A:0xff}
    WhiteSmoke               = RGBA{R:0xf5, G:0xf5, B:0xf5, A:0xff}
    Yellow                   = RGBA{R:0xff, G:0xff, B:0x00, A:0xff}
    YellowGreen              = RGBA{R:0x9a, G:0xcd, B:0x32, A:0xff}
    GoGopherBlue             = RGBA{R:0x00, G:0xad, B:0xd8, A:0xff}
    GoLightBlue              = RGBA{R:0x5d, G:0xc9, B:0xe2, A:0xff}
    GoAqua                   = RGBA{R:0x00, G:0xa2, B:0x9c, A:0xff}
    GoFuchsia                = RGBA{R:0xce, G:0x32, B:0x62, A:0xff}
    GoYellow                 = RGBA{R:0xfd, G:0xdd, B:0x00, A:0xff}
    GoTeal                   = RGBA{R:0x00, G:0x75, B:0x8d, A:0xff}
    GoIndigo                 = RGBA{R:0x40, G:0x2b, B:0x56, A:0xff}
    GoBlack                  = RGBA{R:0x00, G:0x00, B:0x00, A:0xff}
    GoDimGray                = RGBA{R:0x55, G:0x57, B:0x59, A:0xff}
    GoLightGray              = RGBA{R:0xdb, G:0xd9, B:0xd6, A:0xff}
    GoWhite                  = RGBA{R:0xff, G:0xff, B:0xff, A:0xff}
)

func init() {
    // Map contains named colors defined in the SVG 1.1 spec.
    Map = make(map[string]RGBA)
    Map["AliceBlue"] = AliceBlue
    Map["AntiqueWhite"] = AntiqueWhite
    Map["Aqua"] = Aqua
    Map["Aquamarine"] = Aquamarine
    Map["Azure"] = Azure
    Map["Beige"] = Beige
    Map["Bisque"] = Bisque
    Map["Black"] = Black
    Map["BlanchedAlmond"] = BlanchedAlmond
    Map["Blue"] = Blue
    Map["BlueViolet"] = BlueViolet
    Map["Brown"] = Brown
    Map["BurlyWood"] = BurlyWood
    Map["CadetBlue"] = CadetBlue
    Map["Chartreuse"] = Chartreuse
    Map["Chocolate"] = Chocolate
    Map["Coral"] = Coral
    Map["CornflowerBlue"] = CornflowerBlue
    Map["Cornsilk"] = Cornsilk
    Map["Crimson"] = Crimson
    Map["Cyan"] = Cyan
    Map["DarkBlue"] = DarkBlue
    Map["DarkCyan"] = DarkCyan
    Map["DarkGoldenrod"] = DarkGoldenrod
    Map["DarkGray"] = DarkGray
    Map["DarkGreen"] = DarkGreen
    Map["DarkGrey"] = DarkGrey
    Map["DarkKhaki"] = DarkKhaki
    Map["DarkMagenta"] = DarkMagenta
    Map["DarkOliveGreen"] = DarkOliveGreen
    Map["DarkOrange"] = DarkOrange
    Map["DarkOrchid"] = DarkOrchid
    Map["DarkRed"] = DarkRed
    Map["DarkSalmon"] = DarkSalmon
    Map["DarkSeaGreen"] = DarkSeaGreen
    Map["DarkSlateBlue"] = DarkSlateBlue
    Map["DarkSlateGray"] = DarkSlateGray
    Map["DarkSlateGrey"] = DarkSlateGrey
    Map["DarkTurquoise"] = DarkTurquoise
    Map["DarkViolet"] = DarkViolet
    Map["DeepPink"] = DeepPink
    Map["DeepSkyBlue"] = DeepSkyBlue
    Map["DimGray"] = DimGray
    Map["DimGrey"] = DimGrey
    Map["DodgerBlue"] = DodgerBlue
    Map["FireBrick"] = FireBrick
    Map["FloralWhite"] = FloralWhite
    Map["ForestGreen"] = ForestGreen
    Map["Fuchsia"] = Fuchsia
    Map["Gainsboro"] = Gainsboro
    Map["GhostWhite"] = GhostWhite
    Map["Gold"] = Gold
    Map["Goldenrod"] = Goldenrod
    Map["Gray"] = Gray
    Map["Green"] = Green
    Map["GreenYellow"] = GreenYellow
    Map["Grey"] = Grey
    Map["Honeydew"] = Honeydew
    Map["HotPink"] = HotPink
    Map["IndianRed"] = IndianRed
    Map["Indigo"] = Indigo
    Map["Ivory"] = Ivory
    Map["Khaki"] = Khaki
    Map["Lavender"] = Lavender
    Map["LavenderBlush"] = LavenderBlush
    Map["LawnGreen"] = LawnGreen
    Map["LemonChiffon"] = LemonChiffon
    Map["LightBlue"] = LightBlue
    Map["LightCoral"] = LightCoral
    Map["LightCyan"] = LightCyan
    Map["LightGoldenrodYellow"] = LightGoldenrodYellow
    Map["LightGray"] = LightGray
    Map["LightGreen"] = LightGreen
    Map["LightGrey"] = LightGrey
    Map["LightPink"] = LightPink
    Map["LightSalmon"] = LightSalmon
    Map["LightSeaGreen"] = LightSeaGreen
    Map["LightSkyBlue"] = LightSkyBlue
    Map["LightSlateGray"] = LightSlateGray
    Map["LightSlateGrey"] = LightSlateGrey
    Map["LightSteelBlue"] = LightSteelBlue
    Map["LightYellow"] = LightYellow
    Map["Lime"] = Lime
    Map["LimeGreen"] = LimeGreen
    Map["Linen"] = Linen
    Map["Magenta"] = Magenta
    Map["Maroon"] = Maroon
    Map["MediumAquamarine"] = MediumAquamarine
    Map["MediumBlue"] = MediumBlue
    Map["MediumOrchid"] = MediumOrchid
    Map["MediumPurple"] = MediumPurple
    Map["MediumSeaGreen"] = MediumSeaGreen
    Map["MediumSlateBlue"] = MediumSlateBlue
    Map["MediumSpringGreen"] = MediumSpringGreen
    Map["MediumTurquoise"] = MediumTurquoise
    Map["MediumVioletRed"] = MediumVioletRed
    Map["MidnightBlue"] = MidnightBlue
    Map["MintCream"] = MintCream
    Map["MistyRose"] = MistyRose
    Map["Moccasin"] = Moccasin
    Map["NavajoWhite"] = NavajoWhite
    Map["Navy"] = Navy
    Map["OldLace"] = OldLace
    Map["Olive"] = Olive
    Map["OliveDrab"] = OliveDrab
    Map["Orange"] = Orange
    Map["OrangeRed"] = OrangeRed
    Map["Orchid"] = Orchid
    Map["PaleGoldenrod"] = PaleGoldenrod
    Map["PaleGreen"] = PaleGreen
    Map["PaleTurquoise"] = PaleTurquoise
    Map["PaleVioletRed"] = PaleVioletRed
    Map["PapayaWhip"] = PapayaWhip
    Map["PeachPuff"] = PeachPuff
    Map["Peru"] = Peru
    Map["Pink"] = Pink
    Map["Plum"] = Plum
    Map["PowderBlue"] = PowderBlue
    Map["Purple"] = Purple
    Map["Red"] = Red
    Map["RosyBrown"] = RosyBrown
    Map["RoyalBlue"] = RoyalBlue
    Map["SaddleBrown"] = SaddleBrown
    Map["Salmon"] = Salmon
    Map["SandyBrown"] = SandyBrown
    Map["SeaGreen"] = SeaGreen
    Map["Seashell"] = Seashell
    Map["Sienna"] = Sienna
    Map["Silver"] = Silver
    Map["SkyBlue"] = SkyBlue
    Map["SlateBlue"] = SlateBlue
    Map["SlateGray"] = SlateGray
    Map["SlateGrey"] = SlateGrey
    Map["Snow"] = Snow
    Map["SpringGreen"] = SpringGreen
    Map["SteelBlue"] = SteelBlue
    Map["Tan"] = Tan
    Map["Teal"] = Teal
    Map["Thistle"] = Thistle
    Map["Tomato"] = Tomato
    Map["Turquoise"] = Turquoise
    Map["Violet"] = Violet
    Map["Wheat"] = Wheat
    Map["White"] = White
    Map["WhiteSmoke"] = WhiteSmoke
    Map["Yellow"] = Yellow
    Map["YellowGreen"] = YellowGreen
    Map["GoGopherBlue"] = GoGopherBlue
    Map["GoLightBlue"] = GoLightBlue
    Map["GoAqua"] = GoAqua
    Map["GoFuchsia"] = GoFuchsia
    Map["GoYellow"] = GoYellow
    Map["GoTeal"] = GoTeal
    Map["GoIndigo"] = GoIndigo
    Map["GoBlack"] = GoBlack
    Map["GoDimGray"] = GoDimGray
    Map["GoLightGray"] = GoLightGray
    Map["GoWhite"] = GoWhite

    // Der Slice 'Names' enthält die Namen aller Farben der SVG 1.1 Spezifikation.
    // Auf die Besonderheit betr. Gross-/Kleinschreibung ist weiter oben bereits
    // eingegangen worden. Jedes Element dieses Slices findet sich als Schlüssel
    // in der Variable 'Map'.
    Names = make([]string, 158)
    Names[0] = "AliceBlue"
    Names[1] = "AntiqueWhite"
    Names[2] = "Aqua"
    Names[3] = "Aquamarine"
    Names[4] = "Azure"
    Names[5] = "Beige"
    Names[6] = "Bisque"
    Names[7] = "Black"
    Names[8] = "BlanchedAlmond"
    Names[9] = "Blue"
    Names[10] = "BlueViolet"
    Names[11] = "Brown"
    Names[12] = "BurlyWood"
    Names[13] = "CadetBlue"
    Names[14] = "Chartreuse"
    Names[15] = "Chocolate"
    Names[16] = "Coral"
    Names[17] = "CornflowerBlue"
    Names[18] = "Cornsilk"
    Names[19] = "Crimson"
    Names[20] = "Cyan"
    Names[21] = "DarkBlue"
    Names[22] = "DarkCyan"
    Names[23] = "DarkGoldenrod"
    Names[24] = "DarkGray"
    Names[25] = "DarkGreen"
    Names[26] = "DarkGrey"
    Names[27] = "DarkKhaki"
    Names[28] = "DarkMagenta"
    Names[29] = "DarkOliveGreen"
    Names[30] = "DarkOrange"
    Names[31] = "DarkOrchid"
    Names[32] = "DarkRed"
    Names[33] = "DarkSalmon"
    Names[34] = "DarkSeaGreen"
    Names[35] = "DarkSlateBlue"
    Names[36] = "DarkSlateGray"
    Names[37] = "DarkSlateGrey"
    Names[38] = "DarkTurquoise"
    Names[39] = "DarkViolet"
    Names[40] = "DeepPink"
    Names[41] = "DeepSkyBlue"
    Names[42] = "DimGray"
    Names[43] = "DimGrey"
    Names[44] = "DodgerBlue"
    Names[45] = "FireBrick"
    Names[46] = "FloralWhite"
    Names[47] = "ForestGreen"
    Names[48] = "Fuchsia"
    Names[49] = "Gainsboro"
    Names[50] = "GhostWhite"
    Names[51] = "Gold"
    Names[52] = "Goldenrod"
    Names[53] = "Gray"
    Names[54] = "Green"
    Names[55] = "GreenYellow"
    Names[56] = "Grey"
    Names[57] = "Honeydew"
    Names[58] = "HotPink"
    Names[59] = "IndianRed"
    Names[60] = "Indigo"
    Names[61] = "Ivory"
    Names[62] = "Khaki"
    Names[63] = "Lavender"
    Names[64] = "LavenderBlush"
    Names[65] = "LawnGreen"
    Names[66] = "LemonChiffon"
    Names[67] = "LightBlue"
    Names[68] = "LightCoral"
    Names[69] = "LightCyan"
    Names[70] = "LightGoldenrodYellow"
    Names[71] = "LightGray"
    Names[72] = "LightGreen"
    Names[73] = "LightGrey"
    Names[74] = "LightPink"
    Names[75] = "LightSalmon"
    Names[76] = "LightSeaGreen"
    Names[77] = "LightSkyBlue"
    Names[78] = "LightSlateGray"
    Names[79] = "LightSlateGrey"
    Names[80] = "LightSteelBlue"
    Names[81] = "LightYellow"
    Names[82] = "Lime"
    Names[83] = "LimeGreen"
    Names[84] = "Linen"
    Names[85] = "Magenta"
    Names[86] = "Maroon"
    Names[87] = "MediumAquamarine"
    Names[88] = "MediumBlue"
    Names[89] = "MediumOrchid"
    Names[90] = "MediumPurple"
    Names[91] = "MediumSeaGreen"
    Names[92] = "MediumSlateBlue"
    Names[93] = "MediumSpringGreen"
    Names[94] = "MediumTurquoise"
    Names[95] = "MediumVioletRed"
    Names[96] = "MidnightBlue"
    Names[97] = "MintCream"
    Names[98] = "MistyRose"
    Names[99] = "Moccasin"
    Names[100] = "NavajoWhite"
    Names[101] = "Navy"
    Names[102] = "OldLace"
    Names[103] = "Olive"
    Names[104] = "OliveDrab"
    Names[105] = "Orange"
    Names[106] = "OrangeRed"
    Names[107] = "Orchid"
    Names[108] = "PaleGoldenrod"
    Names[109] = "PaleGreen"
    Names[110] = "PaleTurquoise"
    Names[111] = "PaleVioletRed"
    Names[112] = "PapayaWhip"
    Names[113] = "PeachPuff"
    Names[114] = "Peru"
    Names[115] = "Pink"
    Names[116] = "Plum"
    Names[117] = "PowderBlue"
    Names[118] = "Purple"
    Names[119] = "Red"
    Names[120] = "RosyBrown"
    Names[121] = "RoyalBlue"
    Names[122] = "SaddleBrown"
    Names[123] = "Salmon"
    Names[124] = "SandyBrown"
    Names[125] = "SeaGreen"
    Names[126] = "Seashell"
    Names[127] = "Sienna"
    Names[128] = "Silver"
    Names[129] = "SkyBlue"
    Names[130] = "SlateBlue"
    Names[131] = "SlateGray"
    Names[132] = "SlateGrey"
    Names[133] = "Snow"
    Names[134] = "SpringGreen"
    Names[135] = "SteelBlue"
    Names[136] = "Tan"
    Names[137] = "Teal"
    Names[138] = "Thistle"
    Names[139] = "Tomato"
    Names[140] = "Turquoise"
    Names[141] = "Violet"
    Names[142] = "Wheat"
    Names[143] = "White"
    Names[144] = "WhiteSmoke"
    Names[145] = "Yellow"
    Names[146] = "YellowGreen"
    Names[147] = "GoGopherBlue"
    Names[148] = "GoLightBlue"
    Names[149] = "GoAqua"
    Names[150] = "GoFuchsia"
    Names[151] = "GoYellow"
    Names[152] = "GoTeal"
    Names[153] = "GoIndigo"
    Names[154] = "GoBlack"
    Names[155] = "GoDimGray"
    Names[156] = "GoLightGray"
    Names[157] = "GoWhite"
}
